function(ConfigureCopyScript name script_name pattern path)
	set(ENV_EXPORT_COPY_DLLS_NAME "Qt5")
	set(ENV_EXPORT_COPY_DLLS_SRC_PATH "${path}")
	set(ENV_EXPORT_COPY_DLLS_PATTERN "${pattern}")
	configure_file("${PROJECT_SOURCE_DIR}/script/copy_dlls.bat.in" "${CMAKE_BINARY_DIR}/copy_${script_name}_dlls.bat")
	message(STATUS "Configured copy script for ${name} to copy from ${path}")
endfunction()